import { Node, Edge } from 'reactflow';
import { FlowNode } from '../flowchartData';

export const task4Nodes: FlowNode[] = [
  {
    id: '1',
    type: 'custom',
    position: { x: 400, y: 50 },
    data: {
      label: 'Início',
      type: 'start',
      description: 'Início do processo de matrícula',
    },
  },
  {
    id: '2',
    type: 'custom',
    position: { x: 400, y: 150 },
    data: {
      label: 'Divulgação Período de Matrícula e Exames',
      type: 'process',
      description: 'Comunicação dos prazos e procedimentos',
      details: ['Publicar datas importantes', 'Divulgar requisitos e documentação'],
    },
  },
  {
    id: '3',
    type: 'custom',
    position: { x: 400, y: 250 },
    data: {
      label: 'Pré-Cadastro Online para Exame de Acesso',
      type: 'process',
      description: 'Candidato realiza inscrição inicial',
      details: ['Preencher formulário de inscrição', 'Informar dados pessoais'],
    },
  },
  {
    id: '4',
    type: 'custom',
    position: { x: 400, y: 350 },
    data: {
      label: 'Upload de Documentos',
      type: 'process',
      description: 'Certificado Ensino Médio, BI, Fotografias',
      details: ['Certificado de conclusão do ensino médio', 'Bilhete de Identidade', 'Fotografias tipo passe'],
    },
  },
  {
    id: '5',
    type: 'custom',
    position: { x: 400, y: 450 },
    data: {
      label: 'Validação Automática de Requisitos Mínimos',
      type: 'process',
      description: 'Sistema verifica documentos',
      details: ['Verificar presença de todos documentos', 'Validar formato dos arquivos'],
    },
  },
  {
    id: '6',
    type: 'custom',
    position: { x: 400, y: 550 },
    data: {
      label: 'Atende Requisitos?',
      type: 'gateway',
      description: 'Validação dos requisitos mínimos',
    },
  },
  {
    id: '7',
    type: 'custom',
    position: { x: 650, y: 650 },
    data: {
      label: 'Notificar Eliminação',
      type: 'process',
      description: 'Candidato não atende aos requisitos',
      details: ['Enviar notificação de eliminação', 'Informar motivo da reprovação'],
    },
  },
  {
    id: '8',
    type: 'custom',
    position: { x: 650, y: 750 },
    data: {
      label: 'Fim',
      type: 'end',
      description: 'Processo encerrado - eliminado',
    },
  },
  {
    id: '9',
    type: 'custom',
    position: { x: 400, y: 700 },
    data: {
      label: 'Gerar Boleto Taxa de Inscrição',
      type: 'process',
      description: 'Emitir documento de pagamento',
      details: ['Gerar referência de pagamento', 'Enviar boleto por email'],
    },
  },
  {
    id: '10',
    type: 'custom',
    position: { x: 400, y: 800 },
    data: {
      label: 'Pagamento da Taxa de Inscrição',
      type: 'process',
      description: 'Candidato efetua o pagamento',
    },
  },
  {
    id: '11',
    type: 'custom',
    position: { x: 400, y: 900 },
    data: {
      label: 'Pagamento Confirmado?',
      type: 'gateway',
      description: 'Verificação de confirmação bancária',
    },
  },
  {
    id: '12',
    type: 'custom',
    position: { x: 650, y: 900 },
    data: {
      label: 'Lembrar Pagamento',
      type: 'process',
      description: 'Enviar notificação de pendência',
    },
  },
  {
    id: '13',
    type: 'custom',
    position: { x: 650, y: 1000 },
    data: {
      label: 'Aguardar Confirmação',
      type: 'process',
      description: 'Esperar validação do pagamento',
    },
  },
  {
    id: '14',
    type: 'custom',
    position: { x: 400, y: 1050 },
    data: {
      label: 'Emissão do Cartão de Identificação',
      type: 'process',
      description: 'Gerar cartão para exame',
      details: ['Criar cartão com foto e número', 'Disponibilizar para impressão'],
    },
  },
  {
    id: '15',
    type: 'custom',
    position: { x: 400, y: 1150 },
    data: {
      label: 'Realização do Exame de Acesso',
      type: 'process',
      description: '15-19 Setembro',
      details: ['Aplicar provas presenciais', 'Registrar presença dos candidatos'],
    },
  },
  {
    id: '16',
    type: 'custom',
    position: { x: 400, y: 1250 },
    data: {
      label: 'Correção das Provas',
      type: 'process',
      description: 'Avaliar desempenho dos candidatos',
      details: ['Corrigir provas objetivas', 'Calcular notas finais'],
    },
  },
  {
    id: '17',
    type: 'custom',
    position: { x: 400, y: 1350 },
    data: {
      label: 'Publicação da Lista de Aprovados',
      type: 'process',
      description: 'Divulgar resultados oficiais',
      details: ['Publicar lista ordenada por classificação', 'Notificar candidatos'],
    },
  },
  {
    id: '18',
    type: 'custom',
    position: { x: 400, y: 1450 },
    data: {
      label: 'Aprovado no Exame?',
      type: 'gateway',
      description: 'Verificar aprovação',
    },
  },
  {
    id: '19',
    type: 'custom',
    position: { x: 650, y: 1550 },
    data: {
      label: 'Notificar "Não Aprovado"',
      type: 'process',
      description: 'Informar reprovação',
    },
  },
  {
    id: '20',
    type: 'custom',
    position: { x: 650, y: 1650 },
    data: {
      label: 'Fim',
      type: 'end',
      description: 'Processo encerrado - reprovado',
    },
  },
  {
    id: '21',
    type: 'custom',
    position: { x: 400, y: 1600 },
    data: {
      label: 'Seleção do Curso por Ordem de Classificação',
      type: 'process',
      description: 'Candidato escolhe curso desejado',
      details: ['Listar cursos disponíveis', 'Registrar preferência do candidato'],
    },
  },
  {
    id: '22',
    type: 'custom',
    position: { x: 400, y: 1700 },
    data: {
      label: 'Vaga Disponível no Curso Escolhido?',
      type: 'gateway',
      description: 'Verificar disponibilidade de vagas',
    },
  },
  {
    id: '23',
    type: 'custom',
    position: { x: 150, y: 1800 },
    data: {
      label: 'Oferecer Curso Alternativo',
      type: 'process',
      description: 'Sugerir outras opções',
      details: ['Listar cursos com vagas', 'Apresentar cursos relacionados'],
    },
  },
  {
    id: '24',
    type: 'custom',
    position: { x: 150, y: 1900 },
    data: {
      label: 'Aceita Curso Alternativo?',
      type: 'gateway',
      description: 'Decisão do candidato',
    },
  },
  {
    id: '25',
    type: 'custom',
    position: { x: -50, y: 2000 },
    data: {
      label: 'Notificar Desistência',
      type: 'process',
      description: 'Registrar não aceitação',
    },
  },
  {
    id: '26',
    type: 'custom',
    position: { x: -50, y: 2100 },
    data: {
      label: 'Fim',
      type: 'end',
      description: 'Processo encerrado - desistência',
    },
  },
  {
    id: '27',
    type: 'custom',
    position: { x: 150, y: 2050 },
    data: {
      label: 'Atribuição ao Curso Alternativo',
      type: 'process',
      description: 'Confirmar curso alternativo',
    },
  },
  {
    id: '28',
    type: 'custom',
    position: { x: 400, y: 1900 },
    data: {
      label: 'Confirmação da Vaga no Curso',
      type: 'process',
      description: 'Reservar vaga para o candidato',
      details: ['Registrar alocação da vaga', 'Gerar confirmação'],
    },
  },
  {
    id: '29',
    type: 'custom',
    position: { x: 400, y: 2150 },
    data: {
      label: 'Upload de Documentos Definitivos',
      type: 'process',
      description: 'Original do Certificado',
      details: ['Enviar documentos originais digitalizados', 'Verificar autenticidade'],
    },
  },
  {
    id: '30',
    type: 'custom',
    position: { x: 400, y: 2250 },
    data: {
      label: 'Validação Final de Documentos',
      type: 'process',
      description: 'Conferência documental',
    },
  },
  {
    id: '31',
    type: 'custom',
    position: { x: 400, y: 2350 },
    data: {
      label: 'Gerar Boleto de Taxa de Matrícula',
      type: 'process',
      description: 'Emitir documento de pagamento',
    },
  },
  {
    id: '32',
    type: 'custom',
    position: { x: 400, y: 2450 },
    data: {
      label: 'Pagamento da Taxa de Matrícula',
      type: 'process',
      description: 'Efetuar pagamento da matrícula',
    },
  },
  {
    id: '33',
    type: 'custom',
    position: { x: 400, y: 2550 },
    data: {
      label: 'Pagamento Confirmado?',
      type: 'gateway',
      description: 'Verificar confirmação bancária',
    },
  },
  {
    id: '34',
    type: 'custom',
    position: { x: 650, y: 2550 },
    data: {
      label: 'Lembrar Pagamento',
      type: 'process',
      description: 'Notificar pendência',
    },
  },
  {
    id: '35',
    type: 'custom',
    position: { x: 650, y: 2650 },
    data: {
      label: 'Aguardar Confirmação',
      type: 'process',
      description: 'Esperar validação',
    },
  },
  {
    id: '36',
    type: 'custom',
    position: { x: 400, y: 2700 },
    data: {
      label: 'Atribuição Automática de Turma',
      type: 'process',
      description: 'Alocar estudante em turma',
      details: ['Verificar disponibilidade de vagas', 'Registrar em turma'],
    },
  },
  {
    id: '37',
    type: 'custom',
    position: { x: 400, y: 2800 },
    data: {
      label: 'Seleção de Disciplinas no Sistema Acadêmico',
      type: 'process',
      description: 'Escolher disciplinas do semestre',
      details: ['Listar disciplinas obrigatórias', 'Permitir seleção de optativas'],
    },
  },
  {
    id: '38',
    type: 'custom',
    position: { x: 400, y: 2900 },
    data: {
      label: 'Confirmação de Horário',
      type: 'process',
      description: 'Verificar disponibilidade',
    },
  },
  {
    id: '39',
    type: 'custom',
    position: { x: 400, y: 3000 },
    data: {
      label: 'Conflito de Horário?',
      type: 'gateway',
      description: 'Verificar sobreposição',
    },
  },
  {
    id: '40',
    type: 'custom',
    position: { x: 650, y: 3000 },
    data: {
      label: 'Ajustar Seleção de Disciplinas',
      type: 'process',
      description: 'Resolver conflitos',
    },
  },
  {
    id: '41',
    type: 'custom',
    position: { x: 400, y: 3150 },
    data: {
      label: 'Gerar Comprovante Definitivo de Matrícula',
      type: 'process',
      description: 'Documento oficial de matrícula',
      details: ['Gerar PDF com dados da matrícula', 'Enviar por email'],
    },
  },
  {
    id: '42',
    type: 'custom',
    position: { x: 400, y: 3250 },
    data: {
      label: 'Ativação de Acesso aos Sistemas',
      type: 'process',
      description: 'Moodle, Email Institucional',
      details: ['Criar conta no Moodle', 'Ativar email institucional', 'Gerar credenciais de acesso'],
    },
  },
  {
    id: '43',
    type: 'custom',
    position: { x: 400, y: 3350 },
    data: {
      label: 'Integração com Biblioteca',
      type: 'process',
      description: 'Cadastro Automático',
      details: ['Criar registro na biblioteca', 'Habilitar empréstimos'],
    },
  },
  {
    id: '44',
    type: 'custom',
    position: { x: 400, y: 3450 },
    data: {
      label: 'É Caloiro?',
      type: 'gateway',
      description: 'Primeiro ano?',
    },
  },
  {
    id: '45',
    type: 'custom',
    position: { x: 200, y: 3550 },
    data: {
      label: 'Incluir em Programa de Receção a Caloiros',
      type: 'process',
      description: 'Cadastrar em atividades de integração',
      details: ['Registrar em eventos de boas-vindas', 'Agendar orientação acadêmica'],
    },
  },
  {
    id: '46',
    type: 'custom',
    position: { x: 600, y: 3550 },
    data: {
      label: 'Atualizar Dados do Estudante',
      type: 'process',
      description: 'Manter registro atualizado',
    },
  },
  {
    id: '47',
    type: 'custom',
    position: { x: 400, y: 3700 },
    data: {
      label: 'Entrega de Cartão de Estudante',
      type: 'process',
      description: 'Emitir cartão físico',
      details: ['Produzir cartão com foto', 'Agendar retirada'],
    },
  },
  {
    id: '48',
    type: 'custom',
    position: { x: 400, y: 3800 },
    data: {
      label: 'Orientações Acadêmicas Finais',
      type: 'process',
      description: 'Informações importantes',
      details: ['Explicar normas acadêmicas', 'Apresentar calendário letivo'],
    },
  },
  {
    id: '49',
    type: 'custom',
    position: { x: 400, y: 3900 },
    data: {
      label: 'Fim',
      type: 'end',
      description: 'Matrícula concluída com sucesso',
    },
  },
];

export const task4Edges: Edge[] = [
  { id: 'e1-2', source: '1', target: '2', animated: true },
  { id: 'e2-3', source: '2', target: '3', animated: true },
  { id: 'e3-4', source: '3', target: '4', animated: true },
  { id: 'e4-5', source: '4', target: '5', animated: true },
  { id: 'e5-6', source: '5', target: '6', animated: true },
  { id: 'e6-7', source: '6', target: '7', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e7-8', source: '7', target: '8', style: { stroke: '#dc2626' } },
  { id: 'e6-9', source: '6', target: '9', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e9-10', source: '9', target: '10', animated: true },
  { id: 'e10-11', source: '10', target: '11', animated: true },
  { id: 'e11-12', source: '11', target: '12', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e12-13', source: '12', target: '13' },
  { id: 'e13-11', source: '13', target: '11', type: 'smoothstep', style: { stroke: '#f59e0b' } },
  { id: 'e11-14', source: '11', target: '14', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e14-15', source: '14', target: '15', animated: true },
  { id: 'e15-16', source: '15', target: '16', animated: true },
  { id: 'e16-17', source: '16', target: '17', animated: true },
  { id: 'e17-18', source: '17', target: '18', animated: true },
  { id: 'e18-19', source: '18', target: '19', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e19-20', source: '19', target: '20', style: { stroke: '#dc2626' } },
  { id: 'e18-21', source: '18', target: '21', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e21-22', source: '21', target: '22', animated: true },
  { id: 'e22-23', source: '22', target: '23', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e23-24', source: '23', target: '24' },
  { id: 'e24-25', source: '24', target: '25', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e25-26', source: '25', target: '26', style: { stroke: '#dc2626' } },
  { id: 'e24-27', source: '24', target: '27', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e27-29', source: '27', target: '29', type: 'smoothstep' },
  { id: 'e22-28', source: '22', target: '28', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e28-29', source: '28', target: '29', animated: true },
  { id: 'e29-30', source: '29', target: '30', animated: true },
  { id: 'e30-31', source: '30', target: '31', animated: true },
  { id: 'e31-32', source: '31', target: '32', animated: true },
  { id: 'e32-33', source: '32', target: '33', animated: true },
  { id: 'e33-34', source: '33', target: '34', label: 'Não', style: { stroke: '#dc2626' } },
  { id: 'e34-35', source: '34', target: '35' },
  { id: 'e35-33', source: '35', target: '33', type: 'smoothstep', style: { stroke: '#f59e0b' } },
  { id: 'e33-36', source: '33', target: '36', label: 'Sim', style: { stroke: '#16a34a' } },
  { id: 'e36-37', source: '36', target: '37', animated: true },
  { id: 'e37-38', source: '37', target: '38', animated: true },
  { id: 'e38-39', source: '38', target: '39', animated: true },
  { id: 'e39-40', source: '39', target: '40', label: 'Sim', style: { stroke: '#dc2626' } },
  { id: 'e40-37', source: '40', target: '37', type: 'smoothstep', style: { stroke: '#f59e0b' } },
  { id: 'e39-41', source: '39', target: '41', label: 'Não', style: { stroke: '#16a34a' } },
  { id: 'e41-42', source: '41', target: '42', animated: true },
  { id: 'e42-43', source: '42', target: '43', animated: true },
  { id: 'e43-44', source: '43', target: '44', animated: true },
  { id: 'e44-45', source: '44', target: '45', label: 'Sim', style: { stroke: '#2563eb' } },
  { id: 'e44-46', source: '44', target: '46', label: 'Não' },
  { id: 'e45-47', source: '45', target: '47' },
  { id: 'e46-47', source: '46', target: '47' },
  { id: 'e47-48', source: '47', target: '48', animated: true },
  { id: 'e48-49', source: '48', target: '49', animated: true },
];
